### ISSUE TITLE
Can user open instead of save

### ISSUE THREAD

**Issue by BritaNelson** [dcneiner/Downloadify#45]
Hi,
Downloadify looks like it will work great, but my users want to just open the excel file.
Normal download things have the choice of "Open" or "Save".

Is there any way to "Open" the file when they click the button?

Thanks,
Brita

**Comment by dcneiner** [comment]
I never looked into doing that with Flash (which powers the functionality of Downloadify). My gut says no, since it would still need to save the file to a temporary location so excel could open it. You might be stuck with a traditional server side rendered file if you want it to function like that. Sorry!
